spring:
  application:
    name: rabbit-mq-study
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 在消息没有被路由到指定的queue时将消息返回，而不是丢弃
    publisher-returns: true
    # 作用：生产者到交换器exchange消息有没有发送成功
    # none 值是禁用发布确认模式，是默认值,
    # correlated 值是发布消息成功到交换器后会触发回调方法，如果发送失败会有错误回执，从而触发重试
    # simple 值经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker
    publisher-confirm-type: correlated

    listener:
      simple:
        acknowledge-mode: manual  # 表示消费者消费成功消息以后需要手工的进行签收（ack确认）,默认为 auto
        concurrency: 5  # 同一个队列启动几个消费者
        default-requeue-rejected: true
        max-concurrency: 5  # 启动消费者最大数量
        prefetch: 1
        retry:
          enabled: true   # 重试，如果 为 false 且 listener 发生异常，则会无限次重试，除非手工处理异常
          max-attempts: 3   # 最大重试次数
          initial-interval: 1000
          max-interval: 10000
          multiplier: 1.0    # 时间策略乘数因子


